import re, os

base = os.path.join(os.path.dirname(os.path.abspath(__file__)), os.pardir, os.pardir, os.pardir)
srcpath = os.path.join(base, "src", "server", "game", "DataStores", "DB2Stores.cpp")
src = open(srcpath, encoding="utf-8", errors="replace").read()

pat = re.compile(r'DB2Storage<\s*[^>]+\>\s*\w+\s*\(\s*"([^"]+\.db2)"\s*,\s*&([A-Za-z0-9_]+)::Instance')
found = []
for m in pat.finditer(src):
    found.append((m.group(1), m.group(2)))

seen = set()
uniq = []
for f, l in found:
    if f not in seen:
        seen.add(f)
        uniq.append((f, l))

out = []
out.append("// AUTO-GENERATED by gen_tables.py - do not edit")
out.append("#include \"DB2FileLoader.h\"")
out.append("#include \"DB2LoadInfo.h\"")
out.append("")
out.append("struct DB2TableRef { char const* File; DB2FileLoadInfo const* LoadInfo; };")
out.append("static DB2TableRef const g_tables[] = {")
for f, l in uniq:
    out.append("    { \"%s\", &%s::Instance }," % (f, l))
out.append("};")
out.append("static unsigned int const g_tableCount = sizeof(g_tables)/sizeof(g_tables[0]);")

here = os.path.dirname(os.path.abspath(__file__))
outpath = os.path.join(here, "db2tables.generated.h")
open(outpath, "w", encoding="utf-8").write("\n".join(out))
print("generated %d tables -> %s" % (len(uniq), outpath))